import { StyleSheet, Dimensions, StatusBar } from "react-native";
export const { width, height } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f9fcfc",
    marginTop: StatusBar.currentHeight,
  },
  restaurantHeader: {
    marginTop: -60,
    marginBottom: 8,
    justifyContent: "center",
    alignSelf: "center",
    elevation: 2,
    borderRadius: 6,
    backgroundColor: "#fff",
    width: width - 2,
    padding: 6,
  },
  restaurantTitle: {
    flexDirection: "row",
    borderBottomColor: "#777",
    borderBottomWidth: 0.3,
    paddingBottom: 2,
  },
  subheader: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: -4,
  },
  optionCard: {
    backgroundColor: "#fff",
    padding: 10,
    marginVertical: 8,
    marginHorizontal: 2,
    elevation: 2,
    borderRadius: 4,
  },
  billingTable: {
    backgroundColor: "#fff",
    padding: 10,
    marginTop: 8,
    marginBottom: 2,
    borderRadius: 4,
    marginHorizontal: 2,
  },
  optionrow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginVertical: 4,
  },
  radioRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "baseline",
    marginVertical: 2,
    borderBottomColor: "#ccc",
    borderBottomWidth: 0.2,
  },
  deliveryNotes: {
    paddingHorizontal: 10,
    marginVertical: 20,
    borderColor: "#ddd",
    borderWidth: 0.5,
    borderRadius: 4,
    marginHorizontal: 2,
  },
  optionsLabels: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#000",
  },
  radioLabel: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#000",
  },
  button: {
    marginHorizontal: 1,
    padding: 6,
    height: 45,
    backgroundColor: "#008000",
    alignItems: "center",
    justifyContent: "center",
  },
  totalCount: {
    marginHorizontal: 1,
    padding: 6,
    height: 45,
    backgroundColor: "#fff",
    width: width / 2,
  },
  btnText: {
    textAlign: "center",
    fontSize: 18,
    color: "#ffffff",
    fontWeight: "bold",
    marginLeft: 26,
    textTransform: "uppercase",
  },
  welcomeText: {
    fontSize: 16,
    fontWeight: "bold",
    padding: 2,
  },
  mealText: {
    fontSize: 14,
    fontWeight: "bold",
  },
  calenderView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(30,30,30,0.5)",
  },
  calendarBody: {
    backgroundColor: "white",
    borderRadius: 4,
  },
  buttonClose: {
    borderRadius: 10,
    elevation: 2,
    height: 20,
    width: 20,
    position: "absolute",
    top: -10,
    right: -10,
    backgroundColor: "#fff",
  },
  tipBox: {
    borderWidth: 0.5,
    borderColor: "#777",
    padding: 8,
    marginHorizontal: 10,
    borderRadius: 4,
    margin: 6,
    paddingHorizontal: 14,
  },
  tipText: {
    marginLeft: 30,
    color: "#777",
  },
  billRow: {
    justifyContent: "space-between",
    flexDirection: "row",
    padding: 2,
  },
  billText: {
    fontSize: 16,
    color: "#8c8c8c",
  },
  billTitle: {
    textDecorationLine: "underline",
    marginVertical: 2,
    padding: 2,
    fontSize: 16,
    fontWeight: "bold",
    color: "#777",
  },
  billLink: {
    textTransform: "uppercase",
    color: "#226ccf",
    fontSize: 12,
    fontWeight: "bold",
  },
});
